# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1443656674);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1443656794);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1443656554);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("calendar.list.sortOrder", "2ee5a2de-42a7-47d7-b494-085b9a95517c");
user_pref("calendar.registry.2ee5a2de-42a7-47d7-b494-085b9a95517c.calendar-main-default", true);
user_pref("calendar.registry.2ee5a2de-42a7-47d7-b494-085b9a95517c.calendar-main-in-composite", true);
user_pref("calendar.registry.2ee5a2de-42a7-47d7-b494-085b9a95517c.name", "Home");
user_pref("calendar.registry.2ee5a2de-42a7-47d7-b494-085b9a95517c.type", "storage");
user_pref("calendar.registry.2ee5a2de-42a7-47d7-b494-085b9a95517c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/New_York");
user_pref("calendar.ui.version", 1);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D:4.0.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.2.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1443656674);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.{e2fda1a4-762b-4020-b5ad-a41df1933103}", true);
user_pref("extensions.lastAppVersion", "38.2.0");
user_pref("extensions.lastPlatformVersion", "38.2.0esrpre");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"d\":\"/afs/unity.ncsu.edu/users/a/aravill/.thunderbird/pb4jz6ij.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"e\":true,\"v\":\"4.0.2\",\"st\":1443656433000,\"mt\":1443656432000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.2.0\",\"st\":1440583188000,\"mt\":1440002423000}}}");
user_pref("idle.lastDailyNotification", 1443658580);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "be6d4c5d-1363-48d9-8f6a-480ccb591d7");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "38.2.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.previousBuildID", "20150819123024");
